package com.toy_cns_mon.pub_toy_cns_all_bre_data_rule_editing_suppl;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cns implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public cns() {
    }




}