package com.toy_cns_mon.pub_toy_cns_all_bre_data_rule_editing_suppl;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class panelist_bus_dim implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public panelist_bus_dim() {
    }




}